/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgregarRouteImport } from './routes/agregar'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AutorRouteImport } from './routes/autor'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as JardinRouteImport } from './routes/jardin'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as MasRouteImport } from './routes/mas'
import { Route as PatioRouteImport } from './routes/patio'
import { Route as PlagasRouteImport } from './routes/plagas'
import { Route as ViveroRouteImport } from './routes/vivero'
import { Route as PlantaIdRouteImport } from './routes/planta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgregarRoute = AgregarRouteImport.update({
  id: '/agregar',
  path: '/agregar',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorRoute = AutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const JardinRoute = JardinRouteImport.update({
  id: '/jardin',
  path: '/jardin',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const PatioRoute = PatioRouteImport.update({
  id: '/patio',
  path: '/patio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlagasRoute = PlagasRouteImport.update({
  id: '/plagas',
  path: '/plagas',
  getParentRoute: () => rootRouteImport,
} as any)
const ViveroRoute = ViveroRouteImport.update({
  id: '/vivero',
  path: '/vivero',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaIdRoute = PlantaIdRouteImport.update({
  id: '/planta/$id',
  path: '/planta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/ajustes': typeof AjustesRoute
  '/autor': typeof AutorRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogo': typeof CatalogoRoute
  '/comunidad': typeof ComunidadRoute
  '/jardin': typeof JardinRoute
  '/luna': typeof LunaRoute
  '/mas': typeof MasRoute
  '/patio': typeof PatioRoute
  '/plagas': typeof PlagasRoute
  '/vivero': typeof ViveroRoute
  '/planta/$id': typeof PlantaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/ajustes': typeof AjustesRoute
  '/autor': typeof AutorRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogo': typeof CatalogoRoute
  '/comunidad': typeof ComunidadRoute
  '/jardin': typeof JardinRoute
  '/luna': typeof LunaRoute
  '/mas': typeof MasRoute
  '/patio': typeof PatioRoute
  '/plagas': typeof PlagasRoute
  '/vivero': typeof ViveroRoute
  '/planta/$id': typeof PlantaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/ajustes': typeof AjustesRoute
  '/autor': typeof AutorRoute
  '/bitacora': typeof BitacoraRoute
  '/catalogo': typeof CatalogoRoute
  '/comunidad': typeof ComunidadRoute
  '/jardin': typeof JardinRoute
  '/luna': typeof LunaRoute
  '/mas': typeof MasRoute
  '/patio': typeof PatioRoute
  '/plagas': typeof PlagasRoute
  '/vivero': typeof ViveroRoute
  '/planta/$id': typeof PlantaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agregar'
    | '/ajustes'
    | '/autor'
    | '/bitacora'
    | '/catalogo'
    | '/comunidad'
    | '/jardin'
    | '/luna'
    | '/mas'
    | '/patio'
    | '/plagas'
    | '/vivero'
    | '/planta/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregar'
    | '/ajustes'
    | '/autor'
    | '/bitacora'
    | '/catalogo'
    | '/comunidad'
    | '/jardin'
    | '/luna'
    | '/mas'
    | '/patio'
    | '/plagas'
    | '/vivero'
    | '/planta/$id'
  id:
    | '__root__'
    | '/'
    | '/agregar'
    | '/ajustes'
    | '/autor'
    | '/bitacora'
    | '/catalogo'
    | '/comunidad'
    | '/jardin'
    | '/luna'
    | '/mas'
    | '/patio'
    | '/plagas'
    | '/vivero'
    | '/planta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgregarRoute: typeof AgregarRoute
  AjustesRoute: typeof AjustesRoute
  AutorRoute: typeof AutorRoute
  BitacoraRoute: typeof BitacoraRoute
  CatalogoRoute: typeof CatalogoRoute
  ComunidadRoute: typeof ComunidadRoute
  JardinRoute: typeof JardinRoute
  LunaRoute: typeof LunaRoute
  MasRoute: typeof MasRoute
  PatioRoute: typeof PatioRoute
  PlagasRoute: typeof PlagasRoute
  ViveroRoute: typeof ViveroRoute
  PlantaIdRoute: typeof PlantaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agregar': {
      id: '/agregar'
      path: '/agregar'
      fullPath: '/agregar'
      preLoaderRoute: typeof AgregarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor': {
      id: '/autor'
      path: '/autor'
      fullPath: '/autor'
      preLoaderRoute: typeof AutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jardin': {
      id: '/jardin'
      path: '/jardin'
      fullPath: '/jardin'
      preLoaderRoute: typeof JardinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patio': {
      id: '/patio'
      path: '/patio'
      fullPath: '/patio'
      preLoaderRoute: typeof PatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagas': {
      id: '/plagas'
      path: '/plagas'
      fullPath: '/plagas'
      preLoaderRoute: typeof PlagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vivero': {
      id: '/vivero'
      path: '/vivero'
      fullPath: '/vivero'
      preLoaderRoute: typeof ViveroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planta/$id': {
      id: '/planta/$id'
      path: '/planta/$id'
      fullPath: '/planta/$id'
      preLoaderRoute: typeof PlantaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgregarRoute: AgregarRoute,
  AjustesRoute: AjustesRoute,
  AutorRoute: AutorRoute,
  BitacoraRoute: BitacoraRoute,
  CatalogoRoute: CatalogoRoute,
  ComunidadRoute: ComunidadRoute,
  JardinRoute: JardinRoute,
  LunaRoute: LunaRoute,
  MasRoute: MasRoute,
  PatioRoute: PatioRoute,
  PlagasRoute: PlagasRoute,
  ViveroRoute: ViveroRoute,
  PlantaIdRoute: PlantaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
